name: memverge-examples
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - jupyter
  - jupyterlab
  # Scientific Python stack
  - numpy
  - scipy
  - pandas
  - networkx
  - scikit-learn
  - imbalanced-learn
  # i/o
  - pyarrow
  - s3fs
  # Visualization
  - matplotlib
  - seaborn
